#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""The setup script."""

from setuptools import setup

requirements = ['Click>=6.0',
                'lxml',
                'future']
packages = ['tempest_zigzag']
entry_points = {
    'console_scripts': [
        'tempest-zigzag=tempest_zigzag.cli:main',
    ],
}

setup(
    name='tempest-zigzag',
    version='0.0.0',
    author="rcbops",
    author_email='rcb-deploy@lists.rackspace.com',
    maintainer='rcbops',
    maintainer_email='rcb-deploy@lists.rackspace.com',
    license="Apache Software License 2.0",
    url='https://github.com/rcbops/tempest-zigzag',
    keywords='zigzag',
    description="Add new information to xml generated by tempest",
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        "Programming Language :: Python :: 2",
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Operating System :: OS Independent',
    ],
    install_requires=requirements,
    packages=packages,
    include_package_data=True,
    zip_safe=False,
    entry_points=entry_points,
)
