from __future__ import absolute_import
import re


class TempestTestcaseXml(object):
    """A class that reads xml generated by tempest
    This class is not responsible for writing new xml based on data
    This class only provides an interface to read xml generated by tempest
    """

    _TEMPEST_UUID_RGX = re.compile(r'(\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)')
    _CLASSNAME = re.compile(r'\((.*)\)')

    def __init__(self, xml_element):
        self._xml_element = xml_element

    @property
    def idempotent_id(self):
        """The unique uuid for this test"""
        try:
            return self._TEMPEST_UUID_RGX.search(self.name).group(0)
        except AttributeError:
            return None

    @property
    def classname(self):
        """The value of the 'classname' attribute
        Taken straight from the xml
        """
        # TODO try and reraise
        return self.xml_element.attrib['classname']

    @property
    def classname_in_wrong_place(self):
        """The classname that sometimes appears in the name attribute"""

        return self._CLASSNAME.search(self.name).group(1)

    @property
    def name(self):
        """The value of the 'name' attribute
        Taken straight from the xml
        """
        # TODO try and reraise
        return self.xml_element.attrib['name']

    @property
    def time(self):
        """The value of the 'time' attribute
        Taken straight from the xml
        """
        # TODO try and reraise
        return self.xml_element.attrib['time']

    @property
    def xml_failure_elements(self):
        """The xml child elements with the tag failure
        """
        # TODO try and reraise
        return self.xml_element.findall('failure')

    @property
    def xml_error_elements(self):
        """The xml child elements with the tag error
        """
        # TODO try and reraise
        return self.xml_element.findall('error')

    @property
    def child_elements(self):
        """The xml child elements
        """
        return list(self.xml_element)

    @property
    def xml_element(self):
        """The XML element that was passed in on instantiation
        This is used when we go to reconstruct the finished xml
        called only when we determine its accurate
        """
        return self._xml_element
